### ISSUE TITLE
Sass breaks on error

### ISSUE THREAD

**Issue by janrembold** [virtualidentityag/gulp-frontend-boilerplate#12]
Find a way to keep sass watch alive if error occurs. But keep error log in console.

**Comment by jhadenfeldt** [comment]
That should do the trick:

```
.pipe($.sass({errLogToConsole: true}))
```

**Comment by janrembold** [comment]
Must be something else broken. Current Sass config stays alive within boilerplate code (on Mac), but in larger project the process exits on error. With enabled "errLogToConsole" it breaks in both scenarios. :( I have to do some deeper research.

**Comment by janrembold** [comment]
The current config is doing fine. The breaking task was caused by a misconfiguration.
