### ISSUE TITLE
Activate eslint and make sure the settings match the .editorconfig

### ISSUE THREAD

**Issue by jhadenfeldt** [virtualidentityag/gulp-frontend-boilerplate#15]
Currently there is an eslint task but it is never triggered during build. Furthermore the settings inside the .eslintrc do not match the .editorconfig from virtualidentityag/gulp-frontend-boilerplate#14.

**Comment by janrembold** [comment]
The eslint task was experimental only. Due to lack of experience it's not enabled by now. Would be great to get it cleaned up and ready for productive usage!

**Comment by alxbenz** [comment]
added to new rules and checked with .editorconfig
https://github.com/virtualidentityag/gulp-frontend-boilerplate/pull/65
