### ISSUE TITLE
refactor app folder structure

### ISSUE THREAD

**Issue by janrembold** [virtualidentityag/gulp-frontend-boilerplate#20]
There are some things in our current app folder structure I would love to change:

- remove all basic, medium, complex folder structures
=> replace them with logical separations like headlines, lists, sliders, stages and so on... even though the components are often mixed together, but for example a stage is still a stage even it contains a slider. With this folder structure the partials would be easier to find.

- rename main template files according to the new folder structures. Maybe we need some other navigation structure inside index.html.... Maybe something like an accordion/tabs view?!?
=> this would cleanup the index.html overview and make it easier to find components

- clean up css folder and remove stuff or make them more configurable/component style (e.g. grid components mentioned here: https://github.com/virtualidentityag/gulp-frontend-boilerplate/issues/17)

**Comment by timomayer** [comment]
+1 for that change
we have such a struture in the r* project and i think its much better then basic, medium, complex.

**Comment by janrembold** [comment]
https://github.com/virtualidentityag/gulp-frontend-boilerplate/pull/22
