### ISSUE TITLE
Switch to a new template engine

### ISSUE THREAD

**Issue by timomayer** [virtualidentityag/gulp-frontend-boilerplate#21]
goals:
- template engine is maintained
- syntax does not conflict with angularJS and handlebars
- fast

suggestion:
http://www.zell-weekeat.com/nunjucks-with-gulp/

must have:
- zetzer has to stay in the boilerplate for existing projects.
- introduce a projectConfig.json, default template engine is the new one, if projectConfig exists and templateEngine: 'zetzer' is set, use zetzer as template engine

**Comment by janrembold** [comment]
+1 for Nunjucks

**Comment by timomayer** [comment]
in my oppinion thats more a 3.0 thing or later. i dont feel the need for that switch and handlebars has one benefit: there are handebars forks in nearly every server side language too (php, java, ...)
in one of our projects we now use hbs templates in server and client. i cant find any nunjucks port for java or php
