### ISSUE TITLE
Browser freezes after first sass change

### ISSUE THREAD

**Issue by smohadjer** [virtualidentityag/gulp-frontend-boilerplate#23]
Currently in R project when I change a sass file for the first time after I have started gulp server, browser freezes and I have to restart browser and server to see the change applied. This means every single style change requires a browser/gulp server restart!

**Comment by janrembold** [comment]
I haven't seen that in other projects. There are lots of modifications in R projects boilerplate, right?

**Comment by lhwparis** [comment]
@saeid reason for that is that we include all sass (css) Files directly in html, in newer projects we use a single file in html and include all sass Files with sass include. We have to change roche to the Second approach and it will not freeze anymore

**Comment by smohadjer** [comment]
Then will open a ticket for that. Thanks for the hint.
