### ISSUE TITLE
Add support for JS and SASS source maps

### ISSUE THREAD

**Issue by smohadjer** [virtualidentityag/gulp-frontend-boilerplate#28]
Currently I'm not able to see where the original css rules come from in browsers' dev tools which is making css bug fixing very difficult. Am I missing something or are sass source maps not supported in VI's gulp boilerplate?

**Comment by timomayer** [comment]
https://github.com/floridoo/gulp-sourcemaps

+1

**Comment by markuspl** [comment]
sourcemaps are now implemented

**Comment by smohadjer** [comment]
Yesssss! :)
