### ISSUE TITLE
Favicon generator in boilerplate aufnehmen

### ISSUE THREAD

**Issue by timomayer** [virtualidentityag/gulp-frontend-boilerplate#42]
z.b. mit:
https://www.npmjs.com/package/gulp-favicons

Ziel: Ein Icon (möglichst svg) in den resources ablegen. im dist werden alle favicons generiert die benötigt werden für die verschiedenen browser/geräte.

html markup muss in die boilerplate eingefügt werden für die favicons

**Comment by timomayer** [comment]
@alxbenz kannst du das übernehmen?

**Comment by alxbenz** [comment]
klar, übernehme ich

**Comment by alxbenz** [comment]
PR ist offen #43
