### ISSUE TITLE
Add maxcomplexity to .jshintrc

### ISSUE THREAD

**Issue by smohadjer** [virtualidentityag/gulp-frontend-boilerplate#44]
Hi guys,

It would be a good idea to add a maxcomplexity property to .jshintrc to discourage developers of writing too convoluted functions. I noticed four functions of cyclomatic complexity of 15 to 20 in one jquery plugin today, so it could be more common as one thinks. I recommend a value of 10 based on following quote from http://elijahmanor.com/control-the-complexity-of-your-javascript-functions-with-jshint/

> In the 2nd edition of Steve McConnell’s Code Complete he recommends that a cyclomatic complexity from 0 to 5 is typically fine, but you should be aware if the complexity starts to get in the 6 to 10 range. He further explains that anything over a complexity of 10 you should strongly consider refactoring your code.

@Timo: It seems I don't have permissions to commit changes to this repo, so I couldn't open a pull as you suggested. Git says: Permission to virtualidentityag/gulp-frontend-boilerplate.git denied to smohadjer.

**Comment by alxbenz** [comment]
added maxcomplexity 10 to jshint

**Comment by smohadjer** [comment]
Thanks Alex.
