### ISSUE TITLE
Extend local project config

### ISSUE THREAD

**Issue by janrembold** [virtualidentityag/gulp-frontend-boilerplate#50]
Change internal tasks from fix list to configurable tasks. Extend global configuration with local config to enable/disable tasks and functionality. E.g. disable handlebars/angular/iconfont compiling

**Comment by alxbenz** [comment]
https://github.com/virtualidentityag/gulp-frontend-boilerplate/pull/58
https://github.com/virtualidentityag/gulp-frontend-boilerplate/pull/62
