### ISSUE TITLE
susy reloaded

### ISSUE THREAD

**Issue by timomayer** [virtualidentityag/gulp-frontend-boilerplate#51]
rethink for susy as the default grid. add mixins to generate grid classes by default.

**Comment by janrembold** [comment]
+1 for susy. I removed foundation already.

Please add susy grid mixins and demo site with advanced usage of new susy grid

**Comment by timomayer** [comment]
@SheepFromHeaven is this task done?

**Comment by alxbenz** [comment]
I cleaned up the according branch and added a grid demo.  https://github.com/virtualidentityag/gulp-frontend-boilerplate/pull/96

**Comment by timomayer** [comment]
thanks alex!
