### ISSUE TITLE
Favicon task different outputs in node 5.x and 6.x

### ISSUE THREAD

**Issue by janrembold** [virtualidentityag/gulp-frontend-boilerplate#72]
Tested with node 5.12.0 and 6.3.1. 

Following line is written in different places between those two node versions:
`<link rel="icon" type="image/png" sizes="228x228" href="favicons/coast-228x228.png">` 

Tests for node 6.x are currently disabled. Re-enable them in `/.travis.yml` after bug was fixed

**Comment by alxbenz** [comment]
https://github.com/virtualidentityag/gulp-frontend-boilerplate/pull/97
