### ISSUE TITLE
Disable main-bower-files task in local projectConfig

### ISSUE THREAD

**Issue by janrembold** [virtualidentityag/gulp-frontend-boilerplate#81]

**Comment by alxbenz** [comment]
Rethink main-bower-files task: target folder naming (vendor vs. bower).

**Comment by alxbenz** [comment]
Discussion: Remove bower completly and load the packages via npm. 

To use only one package manager we could remove bower and load everything via npm. This would require a new copy task, which copies the files from "node_modules" to "vendor/etc". The files to copy could be specified inside projectConfig.json.

**Comment by janrembold** [comment]
+1 for removing bower and adding a new copy task from node_modules packages

**Comment by davelosert** [comment]
Instead of copying, why don't you let a bundle-tool like webpack or browserify do this work for you? 
I'd be much more intuitiv to just use ECMA6 `imports` or `requires` to resolve modules needed from the `node_modules` folder? (+ you get tooling and module-resolving support from all common IDEs)

**Comment by janrembold** [comment]
https://github.com/virtualidentityag/gulp-frontend-boilerplate/pull/100
